<a href="https://colab.research.google.com/github/prodramp/DeepWorks/blob/main/PyTorchTutorials/01_All_things_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **All Things Tensor:**
- Building blocks of Deep Learning
- Data i.e. shopping card, logs, images, texts all can be represented as Tensor
- All deep learning libraries supports Tensor as data input and operations
- Tensors are generalized vector and/or matrix
- Tensors are kind of Matrix but still have lots of difference between them
- A matrix is just a 2-D grid of numbers represented a [N x M]
- A tensor is A tensor is generalized matrix. 
  - Can also be a 0-D matrix (a single number), 
  - Can be a 1-D matrix (a vector is actually such a tensor), 
  - Can be 3-D matrix (something like a cube of numbers), 
  - Can also be a higher dimensional structure that is harder to visualize. 
- The dimension of the tensor is called its rank.
- A definitive Tensor is a multi-dimensional array of minimum 3 or more dimensions 
- In Python a tensor is represented as N-Dimensional array (ndarray)

Resources:
- https://www.kdnuggets.com/2018/05/wtf-tensor.html
- https://machinelearningmastery.com/introduction-to-tensors-for-machine-learning/
- https://medium.com/@quantumsteinke/whats-the-difference-between-a-matrix-and-a-tensor-4505fbdc576c
- https://www.marktechpost.com/2021/01/09/getting-started-with-pytorch-in-google-collab-with-free-gpu/


In [1]:
import torch

In [7]:
torch.Tensor([[1,2,3],[3,4,5]])
#torch.Tensor([[1,2,3],[4,5,6]])

tensor([[1., 2., 3.],
        [3., 4., 5.]])

In [26]:
t = torch.Tensor([1,2,3])
print(t)
print(t.shape)
print(type(t))
print(t.dtype)

tensor([1., 2., 3.])
torch.Size([3])
<class 'torch.Tensor'>
torch.float32


In [17]:
t = torch.Tensor([ [[0,1,2,5],[4,5,6, 9], [7,8,9, 8]] , [[0,1,2,5],[4,5,6, 9], [7,8,9, 8]]  ])
print(t)
print(t.shape)
print(type(t))
print(t.dtype)

tensor([[[0., 1., 2., 5.],
         [4., 5., 6., 9.],
         [7., 8., 9., 8.]],

        [[0., 1., 2., 5.],
         [4., 5., 6., 9.],
         [7., 8., 9., 8.]]])
torch.Size([2, 3, 4])
<class 'torch.Tensor'>
torch.float32


In [29]:
#t = torch.zeros(1,5, dtype=torch.int)
t = torch.ones(50,1,50, dtype=torch.float)
print(type(t))
print(t)
print(t.shape)
print(t.dtype)


<class 'torch.Tensor'>
tensor([[[1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.]],

        ...,

        [[1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.]]])
torch.Size([50, 1, 50])
torch.float32


In [36]:
# Randonly 
t = torch.rand(1,1,5) #  dtype=torch.float (not needed, all random values will be float by default)
# random tensor operartion does not support int type
#t = torch.rand(1,5, dtype=torch.int)
print(type(t))
print(t)
print(t.shape)
print(t.dtype)

<class 'torch.Tensor'>
tensor([[[0.8990, 0.7541, 0.4115, 0.9595, 0.7595]]])
torch.Size([1, 1, 5])
torch.float32


In [46]:
# Randonly for normal distribution
# with this the numbers generated will have mean values is 0 and variance as 1 (Gaussian white noise)
t = torch.randn(2,5)
print(type(t))
print(t)
print(t.shape)
print(t.dtype)

<class 'torch.Tensor'>
tensor([[-0.3740,  0.8155,  0.5971, -0.6809, -0.3245],
        [-0.7502, -1.0066,  0.5070,  0.5352, -1.5914]])
torch.Size([2, 5])
torch.float32


In [44]:
t[0][1][4]

tensor(0.6127)

In [47]:
# Conversion of tensor to Pandas Dataframe
# Note: If Tensor has more then 2 dimensions then you would need to process it differently
a = t.tolist()
import pandas as pd
df = pd.DataFrame(a)
df

0         1         2         3         4
0 -0.374029  0.815549  0.597108 -0.680906 -0.324526
1 -0.750211 -1.006602  0.507031  0.535242 -1.591417

In [56]:
from numpy import array
nm = array([
  [[1,2,3],    [4,5,6.1],    [7,8,9]],
  [[11,12,13], [14,15,16], [17,18,19]],
  [[21,22,23], [24,25,26], [27,28,29]],
  ])
print(nm.shape)
print(nm)
print(type(nm))
print(nm.dtype)

(3, 3, 3)
[[[ 1.   2.   3. ]
  [ 4.   5.   6.1]
  [ 7.   8.   9. ]]

 [[11.  12.  13. ]
  [14.  15.  16. ]
  [17.  18.  19. ]]

 [[21.  22.  23. ]
  [24.  25.  26. ]
  [27.  28.  29. ]]]
<class 'numpy.ndarray'>
float64


In [57]:
t = torch.from_numpy(nm)
print(t.shape)
print(t)
print(type(t))
print(t.dtype)

torch.Size([3, 3, 3])
tensor([[[ 1.0000,  2.0000,  3.0000],
         [ 4.0000,  5.0000,  6.1000],
         [ 7.0000,  8.0000,  9.0000]],

        [[11.0000, 12.0000, 13.0000],
         [14.0000, 15.0000, 16.0000],
         [17.0000, 18.0000, 19.0000]],

        [[21.0000, 22.0000, 23.0000],
         [24.0000, 25.0000, 26.0000],
         [27.0000, 28.0000, 29.0000]]], dtype=torch.float64)
<class 'torch.Tensor'>
torch.float64


### **Using torch.ones**

In [58]:
t = torch.ones(5, 5) # 4,4 - 3,5
print(t.shape)
print(t)
print(type(t))
print(t.dtype)

torch.Size([5, 5])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
<class 'torch.Tensor'>
torch.float32


### **Using torch.zeros**

In [59]:
t = torch.zeros(5, 5)
print(t.shape)
print(t)
print(type(t))
print(t.dtype)

torch.Size([5, 5])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
<class 'torch.Tensor'>
torch.float32


### **Using torch.ones_like**

In [61]:
t = torch.rand(5, 3)
print(t)
# Keeping the source tensor shape and type but filling requested data
t_ones = torch.ones_like(t) 
print(f"Ones Tensor: \n {t_ones} \n")
print(t_ones)
print(type(t_ones))
print(t_ones.dtype)

tensor([[0.6045, 0.0166, 0.5515],
        [0.8679, 0.1401, 0.3168],
        [0.0536, 0.0477, 0.0411],
        [0.8044, 0.5896, 0.9260],
        [0.4078, 0.8985, 0.1927]])
Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
<class 'torch.Tensor'>
torch.float32


### **Using torch.zeros_like:**

In [66]:
t = torch.rand(5, 4)
print(t)
# Keeping the source tensor shape and type but filling requested data
t_zeros = torch.zeros_like(t) 
#print(f"Zeros Tensor: \n {t_zeros} \n")
print(t_zeros)
print(type(t_zeros))
print(t_zeros.dtype)

tensor([[0.9761, 0.4466, 0.3771, 0.3334],
        [0.9026, 0.9910, 0.5035, 0.4342],
        [0.4799, 0.4875, 0.8521, 0.4814],
        [0.8896, 0.1712, 0.6240, 0.4646],
        [0.5475, 0.5115, 0.0107, 0.9115]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
<class 'torch.Tensor'>
torch.float32


In [67]:
t = torch.ones(5, 5, dtype=torch.int)
print(t)
print(type(t))
print(t.dtype)
t_rand = torch.rand_like(t, dtype=torch.float)
print(t_rand)
print(type(t_rand))
print(t_rand.dtype)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)
<class 'torch.Tensor'>
torch.int32
tensor([[0.9703, 0.6034, 0.6545, 0.9659, 0.7510],
        [0.8728, 0.3161, 0.9348, 0.4785, 0.7939],
        [0.9256, 0.1844, 0.4914, 0.3556, 0.1348],
        [0.2862, 0.6055, 0.1826, 0.5339, 0.4031],
        [0.3730, 0.4582, 0.9659, 0.2865, 0.5095]])
<class 'torch.Tensor'>
torch.float32


## **Converting torch tensor to Numpy ndarry**

In [68]:
t = t.numpy()
print(t.shape)
print(t)
print(type(t))
print(t.dtype)

(5, 5)
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
<class 'numpy.ndarray'>
int32


# **Tensor Operations**

## **Matrix Multiplication:**
 - T1 of (n x m) dimensions can only be multiplicable with other Tensor of  (m x p). 
 - A x B is not equal to B x A unless both the (n x n) matrix


In [76]:
A = torch.randn(3,4)
B = torch.randn(4,2)
# We are multipling Matrix A with B
result = A.mm(B)
#result = torch.matmul(A, B)
print(result.shape)
print(result)
print(type(result))
print(result.dtype)

torch.Size([3, 2])
tensor([[-3.1766,  1.4652],
        [ 1.3369, -2.0232],
        [-0.7672, -3.8553]])
<class 'torch.Tensor'>
torch.float32


In [72]:
## Following will generate the error 
## as it does not follow the - A (n x m) with B (m x p) notation 
## ----- Will generation the exception
A = torch.randn(3,4)
B = torch.randn(4,2)
# We are multipling Matrix A with B
result = B.mm(A)
print(result.shape)
print(result)
print(type(result))
print(result.dtype)

RuntimeError: ignored

# **Transpose:**
- Transpose changes matrix rows to columns and columns to rows

In [73]:
A = torch.randn(4,4)
t = A.t()
print(t.shape)
print(A)
print("-------------")
print(t)
print(type(t))
print(t.dtype)

torch.Size([4, 4])
tensor([[-0.3669, -1.0673, -0.9142,  0.1216],
        [-0.0885,  1.0181,  1.0415,  0.0914],
        [ 0.7694, -0.6141, -0.4084, -0.2934],
        [ 0.8024,  0.7341, -1.3598, -0.8646]])
-------------
tensor([[-0.3669, -0.0885,  0.7694,  0.8024],
        [-1.0673,  1.0181, -0.6141,  0.7341],
        [-0.9142,  1.0415, -0.4084, -1.3598],
        [ 0.1216,  0.0914, -0.2934, -0.8646]])
<class 'torch.Tensor'>
torch.float32


# **Airthmatic Element-wise Operations:**


## **multiplication by a number**

In [74]:
#A = torch.randn(4,4)
#A = torch.zeros(4,4)
A = torch.ones(4,4)
print(A)
t = A*5
print(t)
print(type(t))
print(t.shape)
print(t.size())
print(t.dtype)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])
<class 'torch.Tensor'>
torch.Size([4, 4])
torch.Size([4, 4])
torch.float32


In [77]:
A = torch.ones(4,4)
print(A)
B = torch.rand(4,5)
print(B)
t = torch.matmul(A, B)
#t = A.matmul(B)
print(t)
print(type(t))
print(t.shape)
print(t.size())
print(t.dtype)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0.9552, 0.5150, 0.9607, 0.4660, 0.8536],
        [0.5186, 0.6494, 0.9207, 0.7565, 0.9486],
        [0.3585, 0.9718, 0.0369, 0.4048, 0.7341],
        [0.6917, 0.0766, 0.1418, 0.1856, 0.5546]])
tensor([[2.5241, 2.2127, 2.0602, 1.8129, 3.0909],
        [2.5241, 2.2127, 2.0602, 1.8129, 3.0909],
        [2.5241, 2.2127, 2.0602, 1.8129, 3.0909],
        [2.5241, 2.2127, 2.0602, 1.8129, 3.0909]])
<class 'torch.Tensor'>
torch.Size([4, 5])
torch.Size([4, 5])
torch.float32


In [85]:
A = torch.rand(3,3)
B = torch.rand(3,5)
out1 = torch.rand_like(A)
#print(A)
print(out1)
torch.matmul(A, B, out=out1) ## Add 'out=out' and check the result 
print(out1)


tensor([[0.4112, 0.2995, 0.1816],
        [0.1086, 0.2312, 0.9298],
        [0.2656, 0.6965, 0.3944]])
tensor([[0.8442, 0.5833, 0.5509, 1.0535, 1.1035],
        [0.5261, 0.4825, 0.7151, 0.6258, 0.6990],
        [0.7580, 0.7570, 0.3462, 1.0048, 1.0968]])


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: UserWarning: An output with one or more elements was resized since it had shape [3, 3], which does not match the required output shape [3, 5].This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  ../aten/src/ATen/native/Resize.cpp:24.)
  


## **Division**

In [88]:
A = torch.randn(4,4)
#A = torch.zeros(4,4)
#A = torch.ones(4,4)
print(A)
t = A/2.0
print(t)
print(type(t))
print(t.shape)
print(t.size())
print(t.dtype)

tensor([[ 2.0710,  0.6421,  0.6936, -0.7469],
        [ 2.9741, -1.0179,  0.8612, -1.2130],
        [ 0.1052,  0.4806,  0.6378,  0.3920],
        [ 1.0115, -0.9665, -0.7306, -0.5000]])
tensor([[ 1.0355,  0.3211,  0.3468, -0.3734],
        [ 1.4871, -0.5089,  0.4306, -0.6065],
        [ 0.0526,  0.2403,  0.3189,  0.1960],
        [ 0.5058, -0.4832, -0.3653, -0.2500]])
<class 'torch.Tensor'>
torch.Size([4, 4])
torch.Size([4, 4])
torch.float32


## **Addition**

In [92]:
#A = torch.randn(4,4)
#A = torch.zeros(4,4)
A = torch.ones(4,4)
print(A)
t = A + 8
#t = A + 8 * A
print(t)
print(type(t))
print(t.shape)
print(t.size())
print(t.dtype)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[9., 9., 9., 9.],
        [9., 9., 9., 9.],
        [9., 9., 9., 9.],
        [9., 9., 9., 9.]])
<class 'torch.Tensor'>
torch.Size([4, 4])
torch.Size([4, 4])
torch.float32


## **Substraction:**

In [94]:
#A = torch.randn(4,4)
#A = torch.zeros(4,4)
A = torch.ones(4,4)
print(A)
t = A - 0.1
print(t)
print(type(t))
print(t.shape)
print(t.size())
print(t.dtype)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0.9000, 0.9000, 0.9000, 0.9000],
        [0.9000, 0.9000, 0.9000, 0.9000],
        [0.9000, 0.9000, 0.9000, 0.9000],
        [0.9000, 0.9000, 0.9000, 0.9000]])
<class 'torch.Tensor'>
torch.Size([4, 4])
torch.Size([4, 4])
torch.float32


## **Division**

In [95]:
#A = torch.randn(4,4)
#A = torch.zeros(4,4)
A = torch.ones(4,4)
print(A)
t = A / 0
print(t)
print(type(t))
print(t.shape)
print(t.size())
print(t.dtype)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[inf, inf, inf, inf],
        [inf, inf, inf, inf],
        [inf, inf, inf, inf],
        [inf, inf, inf, inf]])
<class 'torch.Tensor'>
torch.Size([4, 4])
torch.Size([4, 4])
torch.float32


## **Square Root:**

In [97]:
#A = torch.randn(4,4)
#A = torch.zeros(4,4)
A = torch.ones(4,4)
print(A)
t = A**2
print(t)
print(type(t))
print(t.shape)
print(t.size())
print(t.dtype)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
<class 'torch.Tensor'>
torch.Size([4, 4])
torch.Size([4, 4])
torch.float32


# **Aggregation**

In [100]:
# Summing of all values in the tensor to a single value
#tensor = torch.ones(2,2)
#tensor = torch.zeros(2,2)
tensor = torch.rand(2,2)
print(tensor)
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor([[0.6234, 0.9916],
        [0.2838, 0.4061]])
2.304842948913574 <class 'float'>


# **In-place operations**

In [105]:
tensor = torch.ones(2,2)
#tensor = torch.zeros(2,2)
tensor = torch.rand(2,2)
print(f"{tensor} \n")
#tensor.add_(5)
#tensor.sub_(5)
#tensor.div_(5)
tensor.mul_(5)
print(tensor)

tensor([[0.6219, 0.9041],
        [0.1879, 0.1192]]) 

tensor([[3.1097, 4.5206],
        [0.9393, 0.5961]])


# **Logical Operation**

- Comparision ( >, <, ==, != , >=, <=  )

In [110]:
A = torch.Tensor([[1,2,3], [4,5,6]])
#A = torch.randn(4,4)
#A = torch.zeros(4,4)
#A = torch.ones(4,4)
print(A)
t = A >=5 
print(t)
print(type(t))
print(t.shape)
print(t.size())
print(t.dtype)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[False, False, False],
        [False,  True,  True]])
<class 'torch.Tensor'>
torch.Size([2, 3])
torch.Size([2, 3])
torch.bool


# **Bitwise or Shift Operator**
- Left Shift (<<)
- Right shift (>>)

In [122]:
#A = torch.randn(4,4)
A = torch.zeros(4,4)
#A = torch.ones(4,4)
print(A)
t = A << 5
print(t)
print(type(t))
print(t.shape)
print(t.size())
print(t.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
<class 'torch.Tensor'>
torch.Size([4, 4])
torch.Size([4, 4])
torch.float32


In [125]:
#x = torch.tensor([32, 16, 8])
x = torch.tensor([32.32, 16.16, 8.8])
#y = torch.tensor([1, 1, 1])
y = torch.tensor([1, 2, 3])
z = x << y
p = x >> y
print(z)
print("-------")
print(p)
print(p.dtype)

tensor([64.6400, 64.6400, 70.4000])
-------
tensor([16.1600,  4.0400,  1.1000])
torch.float32


# **Standard numpy-like indexing and slicing:**

In [130]:
#tensor = torch.ones(4, 4)
tensor = torch.rand(4, 4)
print(f"Full Tensor:\n {tensor}")
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Second column: {tensor[:, 1]}")
print(f"Last column: {tensor[..., -1]}")
# assignment to tensor slice
tensor[:,1] = 0
print(tensor)

Full Tensor:
 tensor([[0.9841, 0.3721, 0.8911, 0.7945],
        [0.8968, 0.3479, 0.1619, 0.5238],
        [0.1645, 0.7888, 0.2040, 0.6947],
        [0.8139, 0.3582, 0.8062, 0.0221]])
First row: tensor([0.9841, 0.3721, 0.8911, 0.7945])
First column: tensor([0.9841, 0.8968, 0.1645, 0.8139])
Second column: tensor([0.3721, 0.3479, 0.7888, 0.3582])
Last column: tensor([0.7945, 0.5238, 0.6947, 0.0221])
tensor([[0.9841, 0.0000, 0.8911, 0.7945],
        [0.8968, 0.0000, 0.1619, 0.5238],
        [0.1645, 0.0000, 0.2040, 0.6947],
        [0.8139, 0.0000, 0.8062, 0.0221]])


# **Tensor Reshape Operation**

In [136]:
# Note: Reshaping the Tensor must be a valid reshape
t = torch.tensor([[1, 2], [3, 4], [5, 6]])
print(t)
print(t.shape)
# Reshape Tensor to 2 rows and 3 columns
print(t.view(2, 3))
# Reshape Tensor to 6 rows and -1 columns
print(t.view(6,-1))
# Reshape Tensor to 2/3 rows and adjustable columns
print(t.view(2,-1))
print(t.view(3,-1))
# Reshape Tensor to adjustable rows and  2/3 columns
print(t.view(-1, 2))
print(t.view(-1, 3))
# The following will return an error
#print(t.view(10,-1))
# RuntimeError: shape '[10, -1]' is invalid for input of size 6


tensor([[1, 2],
        [3, 4],
        [5, 6]])
torch.Size([3, 2])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])


# **Tensor Concatnation:**


In [141]:
t = torch.ones(2,2,)
t0 = torch.rand(2,2)
print(t)
print(t0)

t1 = torch.cat([t, t, t0])
t2 = torch.cat([t, t, t0], dim=1)
print(t1)
print(t1.shape)
print(t2)
print(t2.shape)


tensor([[1., 1.],
        [1., 1.]])
tensor([[0.6846, 0.3654],
        [0.1466, 0.7399]])
tensor([[1.0000, 1.0000],
        [1.0000, 1.0000],
        [1.0000, 1.0000],
        [1.0000, 1.0000],
        [0.6846, 0.3654],
        [0.1466, 0.7399]])
torch.Size([6, 2])
tensor([[1.0000, 1.0000, 1.0000, 1.0000, 0.6846, 0.3654],
        [1.0000, 1.0000, 1.0000, 1.0000, 0.1466, 0.7399]])
torch.Size([2, 6])


# **Device for the Tensor**

In [3]:
shape = (2,3,)
t = torch.ones(shape)
print(t)
print(f"Device tensor is stored on: {t.device}")

tensor([[1., 1., 1.],
        [1., 1., 1.]])
Device tensor is stored on: cpu


# **Supporting GPU with PyTorch**

In [4]:
if torch.cuda.is_available():
  print(torch.cuda.device_count())

1


In [5]:
torch.cuda.get_device_name(0)

'Tesla T4'

In [6]:
print(torch.cuda.device_count())

1


In [7]:
if torch.cuda.is_available():
  for i in range(torch.cuda.device_count()):
    print(torch.cuda.get_device_name(i))

Tesla T4


In [7]:
device=torch.device('cuda:0')
print(device)

cuda:0


In [8]:
cuda0 = torch.device('cuda:0')

In [11]:
shape = (2,3,)
t = torch.ones(shape, device=torch.device('cuda:0'))
#t = torch.ones(shape, device=torch.device(cuda0))
#t = torch.zeros(shape, device=torch.device(cuda0))
print(t)
print(f"Device tensor is stored on: {t.device}")

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
Device tensor is stored on: cuda:0


In [12]:
t = torch.rand(shape, device=torch.device(cuda0))
print(t)
print(f"Device tensor is stored on: {t.device}")

tensor([[0.5803, 0.2415, 0.9138],
        [0.5907, 0.1959, 0.9873]], device='cuda:0')
Device tensor is stored on: cuda:0


In [13]:
t = torch.randn(shape, device=torch.device(cuda0))
print(t)
print(f"Device tensor is stored on: {t.device}")

tensor([[ 0.3855,  0.5297, -0.0430],
        [ 1.0148,  1.2021,  0.4993]], device='cuda:0')
Device tensor is stored on: cuda:0


In [6]:
import torch

In [5]:
t = torch.Tensor(100000, 1000,1000)
print(t.shape)

torch.Size([100000, 1000, 1000])


# **Operation directly on GPU**





In [10]:
m1 = torch.ones(3, 2, device=cuda0)
m2 = torch.ones(3, 2, device=cuda0)
print(m1)
print(m2)
m0 = m1 + m2 
m0 = m0 * m0
print(m0)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], device='cuda:0')
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], device='cuda:0')
tensor([[4., 4.],
        [4., 4.],
        [4., 4.]], device='cuda:0')


# **Moving tensor from GPU to CPU**

In [11]:
m00 = m0.cpu()
print(m0)
print(m00)
print("-------------")
m0.cpu()
print(m0)
m0 = m0.cpu()
print(m0)

tensor([[4., 4.],
        [4., 4.],
        [4., 4.]], device='cuda:0')
tensor([[4., 4.],
        [4., 4.],
        [4., 4.]])
-------------
tensor([[4., 4.],
        [4., 4.],
        [4., 4.]], device='cuda:0')
tensor([[4., 4.],
        [4., 4.],
        [4., 4.]])


# **Bridge with NumPy:**

Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.



In [14]:
t = torch.ones(5)
print(f"t: {t}")


n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [15]:
t.add_(1)

print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [17]:
# the following will give the error as add_ is only the Tensor operation now the ndarray specific function
#n.add_(1)