<a href="https://colab.research.google.com/github/prodramp/DeepWorks/blob/main/PyTorchTutorials/02_NeuralNetworkModel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **What we will cover in this Notebook:**
- Creating your very first Network Model
- Understanding input data features to setup correct Network Model
- Setting network model definition and forward functions 

Resources:
- https://www.marktechpost.com/2021/01/09/getting-started-with-pytorch-in-google-collab-with-free-gpu/
- https://towardsdatascience.com/optimize-pytorch-performance-for-speed-and-memory-efficiency-2022-84f453916ea6
- https://www.kdnuggets.com/2020/09/most-complete-guide-pytorch-data-scientists.html
- https://pytorch.org/docs/stable/index.html

# **PyTorch**
- nn.Module
  - Base class for all neural network modules.
  - Your models should also subclass this class.



In [1]:
import torch
import torch.nn as nn

Define your Neural Network Model:
- Class based on nn.Module
- The __init__ part has all the layers defined in the NN model
- The forward() method defined how the data flows from one layer to another inside the network

# **Define your Neural network Model**

In [2]:
class myFirstNeuralNetworkModel(nn.Module):
  def __init__(self):
    super().__init__()
    # This model has no layers
  def forward(self, x):
    # This model does not forward anything
    return x

### **Instantiate your model:**

In [3]:
# creating your model object
model = myFirstNeuralNetworkModel()

In [4]:
print(model)

myFirstNeuralNetworkModel()


# **Define your input tensor data:**

Let's assume that our input data has:
- Total 100 records
  - 100 records of 5 columns or dimensions
  - 100 x [age, income, zipcode, has_house, is_married]
  - Outcome is purchase_house = True or False/ 1 or 0
- Each record has 5 dimesions or fields

In [6]:
t = torch.randn(10, 5)
print(t.shape)
print(t.dtype)
print(t.size)
print(t)

torch.Size([10, 5])
torch.float32
<built-in method size of Tensor object at 0x7fa18b6f07d0>
tensor([[-1.7671, -1.1936, -0.4976,  0.6211, -1.5277],
        [ 0.8632,  0.1708,  0.0863, -1.0231,  0.1336],
        [ 1.0158,  0.8734, -0.8509, -0.8493, -2.1544],
        [ 0.3914, -0.4933, -0.0538,  1.7118, -1.2035],
        [ 0.2626,  1.4175,  0.0684,  1.0486,  1.7696],
        [-1.0415, -0.0479,  1.0422,  0.2048,  1.7533],
        [ 0.8893, -0.4641, -0.3463, -0.9373,  1.5733],
        [-0.0559, -1.5967, -0.0586,  0.8524,  2.0070],
        [-1.0844,  0.3603,  0.8678, -0.8734,  0.8527],
        [-0.5366,  1.4568, -0.2333,  0.2561, -0.9366]])


Creating an object by passing input data through the Model

In [7]:
nnm = model(t)

In [8]:
print(model(t))

tensor([[-1.7671, -1.1936, -0.4976,  0.6211, -1.5277],
        [ 0.8632,  0.1708,  0.0863, -1.0231,  0.1336],
        [ 1.0158,  0.8734, -0.8509, -0.8493, -2.1544],
        [ 0.3914, -0.4933, -0.0538,  1.7118, -1.2035],
        [ 0.2626,  1.4175,  0.0684,  1.0486,  1.7696],
        [-1.0415, -0.0479,  1.0422,  0.2048,  1.7533],
        [ 0.8893, -0.4641, -0.3463, -0.9373,  1.5733],
        [-0.0559, -1.5967, -0.0586,  0.8524,  2.0070],
        [-1.0844,  0.3603,  0.8678, -0.8734,  0.8527],
        [-0.5366,  1.4568, -0.2333,  0.2561, -0.9366]])


In [9]:
print(nnm)

tensor([[-1.7671, -1.1936, -0.4976,  0.6211, -1.5277],
        [ 0.8632,  0.1708,  0.0863, -1.0231,  0.1336],
        [ 1.0158,  0.8734, -0.8509, -0.8493, -2.1544],
        [ 0.3914, -0.4933, -0.0538,  1.7118, -1.2035],
        [ 0.2626,  1.4175,  0.0684,  1.0486,  1.7696],
        [-1.0415, -0.0479,  1.0422,  0.2048,  1.7533],
        [ 0.8893, -0.4641, -0.3463, -0.9373,  1.5733],
        [-0.0559, -1.5967, -0.0586,  0.8524,  2.0070],
        [-1.0844,  0.3603,  0.8678, -0.8734,  0.8527],
        [-0.5366,  1.4568, -0.2333,  0.2561, -0.9366]])


In [10]:
print(nnm.size)

<built-in method size of Tensor object at 0x7fa18b6f07d0>


In [11]:
print(nnm.shape)

torch.Size([10, 5])


In [ ]:
nnm

Until now we have no relationhip between the Tensor and the Model we created.
- The Model definition is empty, it does not handle the input as there are no layers to process the input data
- The forward method does not pass anything 
- The model is EMPTY

# **Lets connect the model and input data (Tensor) together**

### **Concept:**
- Dataset:
  - We have 100 records of 5 dimensions
  - Our output class has 2 values True (1) or False (0)
- First (Input) Layer
  - self.lin1 = nn.Linear(Input_dimensions, input_for_first_hidden_layer)
- Middle Layers (As many as needed)
  - Must have the matrix manipulations working... 
- Last (Output) Layer
  - self.linX = nn.Linear(output_of_previous_layers, output_classes)

In [43]:
class myFirstNeuralNetworkModel(nn.Module):
  def __init__(self):
    super().__init__()
    # This model has 2 Linear layers
    # first layer takes the input  of size 5 and 
    ## First layer INPUT parameter shows the number of dimensions in your data as input to the network
    self.linear1 = nn.Linear(5, 10)
    self.linear2 = nn.Linear(10, 100)
    self.linear3 = nn.Linear(100, 1000)
    self.linear4 = nn.Linear(1000, 10)
    self.linear5 = nn.Linear(10, 2) 
    ## Last layer OUT parameter shows the number of outputs in your nerual network
  def forward(self, x):
    # This model connect the layer outputs in the forward pass
    x = self.linear1(x)
    print(x.shape)
    x = self.linear2(x)
    print(x.shape)
    x = self.linear3(x)
    print(x.shape)
    x = self.linear4(x * x)
    print(x.shape)
    x = self.linear5(x) 
    print(x.shape)
    return x

In [35]:
# t = torch.randn(10, 5)
#t = torch.ones(10, 5)
t = torch.zeros(10, 5)

print(t.shape)
print(t.dtype)
print(t.size)
print(t)

torch.Size([10, 5])
torch.float32
<built-in method size of Tensor object at 0x7fa18b6548f0>
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [44]:
model = myFirstNeuralNetworkModel()
n = model(t)

torch.Size([10, 10])
torch.Size([10, 100])
torch.Size([10, 1000])
torch.Size([10, 10])
torch.Size([10, 2])


In [37]:
print(n.size)
print(n.shape)
print(n)

<built-in method size of Tensor object at 0x7fa18b694290>
torch.Size([10, 2])
tensor([[ 0.0067, -0.2816],
        [ 0.0067, -0.2816],
        [ 0.0067, -0.2816],
        [ 0.0067, -0.2816],
        [ 0.0067, -0.2816],
        [ 0.0067, -0.2816],
        [ 0.0067, -0.2816],
        [ 0.0067, -0.2816],
        [ 0.0067, -0.2816],
        [ 0.0067, -0.2816]], grad_fn=<AddmmBackward0>)


# **Importance of your model size:**
The model object size is the important significance of your inner working of your model
- The size must be:
  - [The total number of the records, total number of output class]

In [ ]:
print(n.shape)

# **Complex Forward Functions**

```
def forward(self, x):
    x1 = self.linear1(x)
    x2 = x + self.linear2(x1)
    x2 = self.linear1(x1)
    x = self.linear3(x2 + 1)
    return x
```

In [45]:
class myFirstNeuralNetworkModel(nn.Module):
  def __init__(self):
    super().__init__()
    # This model has 2 Linear layers
    self.linear1 = nn.Linear(5, 100)
    self.linear2 = nn.Linear(100, 5)
    self.linear3 = nn.Linear(100, 2) 
    ## Last layer OUT parameter shows the number of outputs in your nerual network
  def forward(self, x):
    # This model connect the layer outputs in the forward pass
    x1 = self.linear1(x) # In -> 5, 100, x1 = 5,100
    print(x1.shape)
    x2 = x + self.linear2(x1) #  (5,100) + ( 5, 100) > x2 = (5, 100) 
    print(x2.shape)
    x2 = self.linear1(x2) # x2 => (5, 100)
    print(x2.shape)
    x = self.linear3(x2) # x2 = (5, 100), x3 => (100, 2)  >  x = output dimension: 2
    print(x.shape)
    return x

In [47]:
model = myFirstNeuralNetworkModel()
#t = torch.ones(10, 5)
t = torch.randn(10, 5)
n = model(t)

torch.Size([10, 100])
torch.Size([10, 5])
torch.Size([10, 100])
torch.Size([10, 2])


In [48]:
print(n.size)
print(n.shape)
print(n)

<built-in method size of Tensor object at 0x7fa18b5e27d0>
torch.Size([10, 2])
tensor([[-0.3378,  0.2793],
        [ 0.2274,  0.2114],
        [-0.1512, -0.0526],
        [ 0.7120, -0.1346],
        [-0.6158,  0.4603],
        [-0.4163, -0.4962],
        [ 0.3068, -0.0445],
        [-0.2392,  0.1978],
        [ 0.1622, -0.1470],
        [ 1.1603, -0.5346]], grad_fn=<AddmmBackward0>)


# **Heart Disease Problem**

- https://archive.ics.uci.edu/ml/datasets/heart+disease
- 75 columns, 14 columns are most used and applicable
- Records 303
- Input -> (303, 14)
- Output -> 2 classes -> True and False

In [49]:
import pandas as pd
import numpy as np

In [50]:
df = pd.read_csv('https://raw.githubusercontent.com/prodramp/publiccode/master/datasets/heart.csv')

In [51]:
df_input = pd.DataFrame(df.iloc[:, 0:13])
df_target = pd.DataFrame(df.iloc[:, 13],columns=['target'])

In [53]:
df_input.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal'],
      dtype='object')

In [61]:
df_input

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0     2  
3        2   0     2  
4        2   0     2  
..     ...  ..   ...  
298      1   0     3  
299      1   0     3  
300      1   2     3  
301      1   1     3  
302      1   1     2  

[303 rows x 13 columns]

In [55]:
df_target.columns

Index(['target'], dtype='object')

In [56]:
inputs_np_array = df_input.to_numpy()
targets_np_array = df_target.to_numpy()

In [57]:
inputs_np_array

array([[63.,  1.,  3., ...,  0.,  0.,  1.],
       [37.,  1.,  2., ...,  0.,  0.,  2.],
       [41.,  0.,  1., ...,  2.,  0.,  2.],
       ...,
       [68.,  1.,  0., ...,  1.,  2.,  3.],
       [57.,  1.,  0., ...,  1.,  1.,  3.],
       [57.,  0.,  1., ...,  1.,  1.,  2.]])

In [60]:
##targets_np_array

In [62]:
inputs = torch.from_numpy(np.array(inputs_np_array,dtype='float32'))
targets = torch.from_numpy(np.array(targets_np_array,dtype='float32'))

In [63]:
print(inputs.dtype)
inputs

torch.float32


tensor([[63.,  1.,  3.,  ...,  0.,  0.,  1.],
        [37.,  1.,  2.,  ...,  0.,  0.,  2.],
        [41.,  0.,  1.,  ...,  2.,  0.,  2.],
        ...,
        [68.,  1.,  0.,  ...,  1.,  2.,  3.],
        [57.,  1.,  0.,  ...,  1.,  1.,  3.],
        [57.,  0.,  1.,  ...,  1.,  1.,  2.]])

In [66]:
print(targets.dtype)
#targets

torch.float32


In [64]:
print(len(inputs[0]))
print(len(targets[0]))
print(len(inputs))
print(len(targets))

13
1
303
303


In [67]:
class HeartDiseaseNeuralNetworkModel(nn.Module):
  def __init__(self):
    super().__init__()
    ## 13 input fields will be used a feature, 100 is the hidden layer
    self.linear1 = nn.Linear(13, 100)
    self.linear2 = nn.Linear(100, 10)
    self.linear3 = nn.Linear(10, 2) 
  def forward(self, x):
    x = self.linear1(x)
    print(x.shape)
    x = self.linear2(x)
    print(x.shape)
    x = self.linear3(x)
    print(x.shape)
    return x

In [68]:
hmodel = HeartDiseaseNeuralNetworkModel()

In [69]:
t = torch.randn(303, 13)
print(t.size)
print(t.shape)
print(t)

<built-in method size of Tensor object at 0x7fa18456ad10>
torch.Size([303, 13])
tensor([[-0.0127,  0.1864, -0.8771,  ...,  0.0701,  1.1519,  0.1037],
        [-1.0126, -0.9164,  1.9987,  ...,  0.5491, -0.1197, -1.4073],
        [-1.5335,  2.2798,  0.8377,  ...,  0.5426,  0.5104,  0.0813],
        ...,
        [ 0.4558,  0.8224, -0.2392,  ..., -1.0076,  0.4439,  1.5869],
        [-0.4692,  2.6232,  0.4714,  ...,  1.2742, -2.0115,  1.4356],
        [-0.7731, -0.1559, -1.1514,  ...,  0.3757,  0.3336, -0.5567]])


In [71]:
hm = hmodel(t)
#hm

torch.Size([303, 100])
torch.Size([303, 10])
torch.Size([303, 2])


- **MNIST Problem** 
  - http://yann.lecun.com/exdb/mnist/
  - 60000 records with 28x28 images means - 60,000 images with 784
  - Input -> (60000, 784)
  - Output -> 10 classes -> 0 to 9 digitas  

In [72]:
class MnistNeuralNetworkModel(nn.Module):
  def __init__(self):
    super().__init__()
    ## 13 input fields will be used a feature, 100 is the hidden layer
    self.linear1 = nn.Linear(784, 1000)
    self.linear2 = nn.Linear(1000, 100)
    self.linear3 = nn.Linear(100, 10)
    # self.linear4 = nn.Linear(10, 10) 
  def forward(self, x):
    x = self.linear1(x)
    print(x.shape)
    x = self.linear2(x)
    print(x.shape)
    x = self.linear3(x)
    print(x.shape)
    # x = self.linear4(x)
    # print(x.shape)
    return x

In [73]:
mnist_model = MnistNeuralNetworkModel()

In [74]:
t = torch.randn(60000, 28*28)
print(t.size)
print(t.shape)
print(t)

<built-in method size of Tensor object at 0x7fa184512ef0>
torch.Size([60000, 784])
tensor([[-0.5316,  0.8239,  0.1507,  ..., -1.5605, -0.1413,  1.4407],
        [-0.1634, -2.5075,  1.4369,  ..., -0.6939,  0.2214, -0.7600],
        [ 0.3102,  0.8649,  1.3184,  ...,  0.1262,  0.1938, -1.0319],
        ...,
        [-1.9664,  0.9541, -0.0611,  ...,  0.4118, -0.3367,  1.4187],
        [-1.1042, -0.0286, -0.5741,  ...,  0.2508,  1.0949,  0.2436],
        [ 0.3921,  1.9291,  0.2720,  ..., -0.6574, -0.4779, -0.9592]])


In [75]:
mn = mnist_model(t)

torch.Size([60000, 1000])
torch.Size([60000, 100])
torch.Size([60000, 10])


# **Using nn.Parameters**

Parameters are Tensor subclasses, that have a very special property when used with Module - when they’re assigned as Module attributes they are automatically added to the list of its parameters, and will appear in parameters() iterator

Source:
- https://www.kdnuggets.com/2020/09/most-complete-guide-pytorch-data-scientists.html

# **Custom Linear Layer**

In [76]:
class myCustomLinearLayer(nn.Module):
    def __init__(self,in_size,out_size):
        super().__init__()
        self.weights = nn.Parameter(torch.randn(in_size, out_size))
        self.bias = nn.Parameter(torch.zeros(out_size))
    def forward(self, x):
        return x.mm(self.weights) + self.bias

# **Customer Neural Network**

In [77]:
class myCustomNeuralNet(nn.Module):
    def __init__(self):
        super().__init__()
        # Define all Layers Here
        self.lin1 = myCustomLinearLayer(784,10)
        
    def forward(self, x):
        # Connect the layer Outputs here to define the forward pass
        x = self.lin1(x)
        print(x.shape)
        return x

In [78]:
# ----- Input records and dimensions        
# 100 records of dimensions 784
x = torch.randn((100,784))

In [79]:
model = myCustomNeuralNet()
model(x).size()

torch.Size([100, 10])


torch.Size([100, 10])

In [81]:
class myCrazyNeuralNet(nn.Module):
    def __init__(self):
        super().__init__()
        # Define all Layers Here
        self.lin1 = nn.Linear(784, 30)
        self.lin2 = nn.Linear(30, 784)
        self.lin3 = nn.Linear(30, 10)
        
    def forward(self, x):
        # Connect the layer Outputs here to define the forward pass
        x_lin1 = self.lin1(x)
        print(x_lin1.shape)
        x_lin2 = x + self.lin2(x_lin1)
        print(x_lin2.shape)
        x_lin2 = self.lin1(x_lin2)
        print(x_lin2.shape)
        x = self.lin3(x_lin2)
        print(x.shape)
        return x

In [82]:
crazy_model = myCrazyNeuralNet()

In [83]:
cm = crazy_model(t)

torch.Size([60000, 30])
torch.Size([60000, 784])
torch.Size([60000, 30])
torch.Size([60000, 10])


# **Homework: Understanding Datasets and setting as input and output:**


- Titanic 
  - https://www.kaggle.com/c/titanic
  - Input - 12 columns including survived (output) columns
  - Output - Survived/Not Survived -> T/F || 1/0
  - 891 records
- Supermarket
- Loan Dataset


# **What is next?**
- How the data is loaded into a network?
- How transectional data is processed with PyTorch
- How the image data is processed with PyTorch

# **Supported Neural Network Architecture with PyTorch:**
- nn.Linear
- nn.Conv2d
- nn.MaxPool2d
- nn.ReLU
- nn.BatchNorm2d
- nn.Dropout
- nn.Embedding
- nn.GRU/nn.LSTM
- nn.Softmax
- nn.LogSoftmax
- nn.MultiheadAttention
- nn.TransformerEncoder
- nn.TransformerDecoder