<a href="https://colab.research.google.com/github/prodramp/DeepWorks/blob/main/PyTorchTutorials/02_NeuralNetworkModel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **What we will cover in this Notebook:**
- Creating your very first Network Model
- Understanding input data features to setup correct Network Model
- Setting network model definition and forward functions 

Resources:
- https://www.marktechpost.com/2021/01/09/getting-started-with-pytorch-in-google-collab-with-free-gpu/
- https://towardsdatascience.com/optimize-pytorch-performance-for-speed-and-memory-efficiency-2022-84f453916ea6
- https://www.kdnuggets.com/2020/09/most-complete-guide-pytorch-data-scientists.html
- https://pytorch.org/docs/stable/index.html

# **PyTorch**
- nn.Module
  - Base class for all neural network modules.
  - Your models should also subclass this class.



In [1]:
import torch
import torch.nn as nn

Define your Neural Network Model:
- Class based on nn.Module
- The __init__ part has all the layers defined in the NN model
- The forward() method defined how the data flows from one layer to another inside the network

# **Define your Neural network Model**

In [2]:
class myFirstNeuralNetworkModel(nn.Module):
  def __init__(self):
    super().__init__()
    # This model has no layers
  def forward(self, x):
    # This model does not forward anything
    return x

### **Instantiate your model:**

In [3]:
# creating your model object
model = myFirstNeuralNetworkModel()

In [4]:
print(model)

myFirstNeuralNetworkModel()


# **Define your input tensor data:**

Let's assume that our input data has:
- Total 10 records
  - 10 records of 5 columns or dimensions
  - 10 x [age, income, zipcode, has_house, is_married]
  - Outcome is purchase_house = True or False/ 1 or 0
- Each record has 5 dimesions or fields

In [5]:
t = torch.randn(10, 5)
print(t.shape)
print(t.dtype)
print(t.size)
print(t)

torch.Size([10, 5])
torch.float32
<built-in method size of Tensor object at 0x7fdfb9bf5cb0>
tensor([[-0.3967, -0.1011, -0.6779, -1.0791,  1.8772],
        [ 0.5511,  0.4503,  1.9484, -1.3010, -0.5900],
        [ 0.2392,  0.8913,  0.4005,  0.5860,  0.4417],
        [ 1.1952, -0.8859, -0.6021,  0.1187,  0.1866],
        [ 2.3325, -1.4756,  0.8492, -1.6600, -0.0365],
        [ 0.3559,  0.5877, -0.6701, -1.9684, -0.9035],
        [ 2.1713,  0.6133, -0.1365, -1.4713, -0.8349],
        [-0.2676,  1.4372,  2.2130, -1.5017,  0.8230],
        [ 0.1001,  0.0123, -1.6012, -0.5635,  0.5560],
        [ 0.5800,  0.4658,  0.1531,  0.8169, -0.3353]])


Creating an object by passing input data through the Model

In [6]:
nnm = model(t)

In [7]:
print(model(t))

tensor([[-0.3967, -0.1011, -0.6779, -1.0791,  1.8772],
        [ 0.5511,  0.4503,  1.9484, -1.3010, -0.5900],
        [ 0.2392,  0.8913,  0.4005,  0.5860,  0.4417],
        [ 1.1952, -0.8859, -0.6021,  0.1187,  0.1866],
        [ 2.3325, -1.4756,  0.8492, -1.6600, -0.0365],
        [ 0.3559,  0.5877, -0.6701, -1.9684, -0.9035],
        [ 2.1713,  0.6133, -0.1365, -1.4713, -0.8349],
        [-0.2676,  1.4372,  2.2130, -1.5017,  0.8230],
        [ 0.1001,  0.0123, -1.6012, -0.5635,  0.5560],
        [ 0.5800,  0.4658,  0.1531,  0.8169, -0.3353]])


In [8]:
print(nnm)

tensor([[-0.3967, -0.1011, -0.6779, -1.0791,  1.8772],
        [ 0.5511,  0.4503,  1.9484, -1.3010, -0.5900],
        [ 0.2392,  0.8913,  0.4005,  0.5860,  0.4417],
        [ 1.1952, -0.8859, -0.6021,  0.1187,  0.1866],
        [ 2.3325, -1.4756,  0.8492, -1.6600, -0.0365],
        [ 0.3559,  0.5877, -0.6701, -1.9684, -0.9035],
        [ 2.1713,  0.6133, -0.1365, -1.4713, -0.8349],
        [-0.2676,  1.4372,  2.2130, -1.5017,  0.8230],
        [ 0.1001,  0.0123, -1.6012, -0.5635,  0.5560],
        [ 0.5800,  0.4658,  0.1531,  0.8169, -0.3353]])


In [9]:
print(nnm.size)

<built-in method size of Tensor object at 0x7fdfb9bf5cb0>


In [10]:
print(nnm.shape)

torch.Size([10, 5])


In [ ]:
nnm

Until now we have no relationhip between the Tensor and the Model we created.
- The Model definition is empty, it does not handle the input as there are no layers to process the input data
- The forward method does not pass anything 
- The model is EMPTY

# **Lets connect the model and input data (Tensor) together**

### **Concept:**
- Dataset:
  - We have 10 records of 5 dimensions
  - We use 10 records as it is easy to visualize here
  - Our output class has 2 values True (1) or False (0)
- Layers
  - We will add through experimentation

A network with input and output layers:
- First (Input and Output) Layer
  - self.lin1 = nn.Linear(Input_dimensions, output_classes)


In [11]:
class myFirstNeuralNetworkModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear0 = nn.Linear(5, 2)
  def forward(self, x):
    x = self.linear0(x)
    print(x.shape)
    return x

A Network with N hidden layer(s)

- First (Input) Layer
  - self.lin1 = nn.Linear(Input_dimensions, input_for_first_hidden_layer)
- Middle Layers (As many as needed)
  - Must have the matrix manipulations working... 
- Last (Output) Layer
  - self.linX = nn.Linear(output_of_previous_layers, output_classes)

In [21]:
class myFirstNeuralNetworkModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear0 = nn.Linear(5, 10)
    self.linear1 = nn.Linear(10, 2)
  def forward(self, x):
    x = self.linear0(x)
    print(x.shape)
    x = self.linear1(x)
    print(x.shape)
    return x

In [26]:
class myFirstNeuralNetworkModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear0 = nn.Linear(5, 100)
    self.linear1 = nn.Linear(100, 10)
    self.linear2 = nn.Linear(10, 2)
  def forward(self, x):
    x = self.linear0(x)
    print(x.shape)
    x = self.linear1(x + x)
    print(x.shape)
    x = self.linear2(x + x + x )
    print(x.shape)
    return x

In [70]:
class myFirstNeuralNetworkModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear0 = nn.Linear(5, 1000)
    self.linear1 = nn.Linear(1000, 100)
    self.linear2 = nn.Linear(100, 10)
    self.linear3 = nn.Linear(10, 2)
  def forward(self, x):
    x = self.linear0(x)
    print(x.shape)
    x = self.linear1(x)
    print(x.shape)
    x = self.linear2(x)
    print(x.shape)
    x = self.linear3(x)
    print(x.shape)
    return x

Lets Experiment with out Neural Network with various Hidden Layers

In [73]:
class myFirstNeuralNetworkModel(nn.Module):
  def __init__(self):
    super().__init__()
    # first layer takes the input  of size 5 and 
    ## First layer INPUT parameter shows the number of dimensions in your data as input to the network
    self.linear1 = nn.Linear(5, 10)
    self.linear2 = nn.Linear(10, 100)
    self.linear3 = nn.Linear(100, 100)
    self.linear4 = nn.Linear(100, 10)
    self.linear5 = nn.Linear(10, 2) 
    ## Last layer OUT parameter shows the number of outputs in your nerual network
  def forward(self, x):
    #This model connect the layer outputs in the forward pass
    x1 = self.linear1(x)
    print(x.shape)
    x = self.linear2(x1)
    print(x.shape)
    x = self.linear3(x) + self.linear2(x1)
    print(x.shape)
    x = self.linear4(x)
    print(x.shape)
    x = self.linear5(x) 
    print(x.shape)
    return x

In [36]:
# t = torch.randn(10, 5)
#t = torch.ones(10, 5)
t = torch.zeros(10, 5)

print(t.shape)
print(t.dtype)
print(t.size)
print(t)

torch.Size([10, 5])
torch.float32
<built-in method size of Tensor object at 0x7fdfb9b4b050>
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [74]:
model = myFirstNeuralNetworkModel()
n = model(t)

torch.Size([10, 5])
torch.Size([10, 100])
torch.Size([10, 100])
torch.Size([10, 10])
torch.Size([10, 2])


In [34]:
print(n.size)
print(n.shape)
print(n)

<built-in method size of Tensor object at 0x7fdfb9b50350>
torch.Size([10, 2])
tensor([[-0.4644,  0.0802],
        [-0.4644,  0.0802],
        [-0.4644,  0.0802],
        [-0.4644,  0.0802],
        [-0.4644,  0.0802],
        [-0.4644,  0.0802],
        [-0.4644,  0.0802],
        [-0.4644,  0.0802],
        [-0.4644,  0.0802],
        [-0.4644,  0.0802]], grad_fn=<AddmmBackward0>)


# **Importance of your model size:**
The model object size is the important significance of your inner working of your model
- The size must be:
  - [The total number of the records, total number of output class]

In [75]:
print(n.shape)

torch.Size([10, 2])


# **Complex Forward Functions**

```
def forward(self, x):
    x1 = self.linear1(x)
    x2 = x + self.linear2(x1)
    x2 = self.linear1(x1)
    x = self.linear3(x2 + 1)
    return x
```

In [83]:
class myFirstNeuralNetworkModel(nn.Module):
  def __init__(self):
    super().__init__()
    # This model has 2 Linear layers
    self.linear1 = nn.Linear(5, 100)
    self.linear2 = nn.Linear(100, 5)
    self.linear3 = nn.Linear(100, 2) 
    ## Last layer OUT parameter shows the number of outputs in your nerual network
  def forward(self, x):
    # This model connect the layer outputs in the forward pass
    x1 = self.linear1(x) # In -> 5, 100, x1 = 5,100
    print(x1.shape)
    x2 = x + self.linear2(x1) #  (5,100) + ( 5, 100) > x2 = (5, 100) 
    print(x2.shape)
    x2 = self.linear1(x2) # x2 => (5, 100)
    print(x2.shape)
    x = self.linear3(x2) # x2 = (5, 100), x3 => (100, 2)  >  x = output dimension: 2
    print(x.shape)
    return x

In [84]:
model = myFirstNeuralNetworkModel()
#t = torch.ones(10, 5)
t = torch.randn(10, 5)
n = model(t)

torch.Size([10, 100])
torch.Size([10, 5])
torch.Size([10, 100])
torch.Size([10, 2])


In [ ]:
print(n.size)
print(n.shape)
print(n)

# **Heart Disease Problem**

- https://archive.ics.uci.edu/ml/datasets/heart+disease
- 75 columns, 14 columns are most used and applicable
- Records 303
- Input -> (303, 14) - 13 Input features and 1 output or target
- Output -> 2 classes -> True and False

In [85]:
import pandas as pd
import numpy as np

In [86]:
df = pd.read_csv('https://raw.githubusercontent.com/prodramp/publiccode/master/datasets/heart.csv')

In [87]:
df_input = pd.DataFrame(df.iloc[:, 0:13])
df_target = pd.DataFrame(df.iloc[:, 13],columns=['target'])

In [88]:
df_input.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal'],
      dtype='object')

In [89]:
df_input

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0     2  
3        2   0     2  
4        2   0     2  
..     ...  ..   ...  
298      1   0     3  
299      1   0     3  
300      1   2     3  
301      1   1     3  
302      1   1     2  

[303 rows x 13 columns]

In [90]:
df_target.columns

Index(['target'], dtype='object')

In [91]:
df_target

target
0         1
1         1
2         1
3         1
4         1
..      ...
298       0
299       0
300       0
301       0
302       0

[303 rows x 1 columns]

In [92]:
inputs_np_array = df_input.to_numpy()
targets_np_array = df_target.to_numpy()

In [93]:
inputs_np_array

array([[63.,  1.,  3., ...,  0.,  0.,  1.],
       [37.,  1.,  2., ...,  0.,  0.,  2.],
       [41.,  0.,  1., ...,  2.,  0.,  2.],
       ...,
       [68.,  1.,  0., ...,  1.,  2.,  3.],
       [57.,  1.,  0., ...,  1.,  1.,  3.],
       [57.,  0.,  1., ...,  1.,  1.,  2.]])

In [95]:
#targets_np_array

In [96]:
inputs = torch.from_numpy(np.array(inputs_np_array,dtype='float32'))
targets = torch.from_numpy(np.array(targets_np_array,dtype='float32'))

In [97]:
print(inputs.dtype)
inputs

torch.float32


tensor([[63.,  1.,  3.,  ...,  0.,  0.,  1.],
        [37.,  1.,  2.,  ...,  0.,  0.,  2.],
        [41.,  0.,  1.,  ...,  2.,  0.,  2.],
        ...,
        [68.,  1.,  0.,  ...,  1.,  2.,  3.],
        [57.,  1.,  0.,  ...,  1.,  1.,  3.],
        [57.,  0.,  1.,  ...,  1.,  1.,  2.]])

In [100]:
print(targets.dtype)
#targets

torch.float32


In [101]:
print(len(inputs[0]))
print(len(targets[0]))
print(len(inputs))
print(len(targets))

13
1
303
303


In [102]:
class HeartDiseaseNeuralNetworkModel(nn.Module):
  def __init__(self):
    super().__init__()
    ## 13 input fields will be used a feature, 100 is the hidden layer
    self.linear1 = nn.Linear(13, 100)
    self.linear2 = nn.Linear(100, 10)
    self.linear3 = nn.Linear(10, 2) 
  def forward(self, x):
    x = self.linear1(x)
    print(x.shape)
    x = self.linear2(x)
    print(x.shape)
    x = self.linear3(x)
    print(x.shape)
    return x

In [103]:
hmodel = HeartDiseaseNeuralNetworkModel()

In [104]:
t = torch.randn(303, 13)
print(t.size)
print(t.shape)
print(t)

<built-in method size of Tensor object at 0x7fdfb347bb30>
torch.Size([303, 13])
tensor([[-2.6896,  0.3017,  0.0757,  ..., -0.4388, -0.3902, -1.5511],
        [-0.3087,  0.4234,  0.3790,  ...,  0.2994, -0.4438,  0.2984],
        [-0.3291, -0.8033,  0.2888,  ...,  0.1297, -0.0402,  1.3748],
        ...,
        [ 0.8617,  0.3453, -2.1986,  ...,  0.4243, -0.1688, -0.4358],
        [-1.4278, -1.2335, -0.3071,  ...,  0.5604,  0.4311,  1.8974],
        [-1.3927, -3.1249, -1.3504,  ..., -0.0397,  1.3043,  1.3777]])


In [105]:
hm = hmodel(t)
#hm

torch.Size([303, 100])
torch.Size([303, 10])
torch.Size([303, 2])


In [106]:
hm.shape

torch.Size([303, 2])

- **MNIST Problem** 
  - http://yann.lecun.com/exdb/mnist/
  - 60000 records with 28x28 images means - 60,000 images with 784
  - Input -> (60000, 784)
  - Output -> 10 classes -> 0 to 9 digitas  

In [112]:
class MnistNeuralNetworkModel(nn.Module):
  def __init__(self):
    super().__init__()
    ## 13 input fields will be used a feature, 100 is the hidden layer
    self.linear1 = nn.Linear(784, 1000)
    self.linear2 = nn.Linear(1000, 100)
    self.linear3 = nn.Linear(100, 10)
    self.linear4 = nn.Linear(10, 10) 
  def forward(self, x):
    x = self.linear1(x)
    print(x.shape)
    x = self.linear2(x)
    print(x.shape)
    x = self.linear3(x)
    print(x.shape)
    x = self.linear4(x)
    print(x.shape)
    return x

In [113]:
mnist_model = MnistNeuralNetworkModel()

In [109]:
t = torch.randn(60000, 28*28)
print(t.size)
print(t.shape)
print(t)

<built-in method size of Tensor object at 0x7fdfb349b9b0>
torch.Size([60000, 784])
tensor([[ 0.2489, -1.1820,  0.6689,  ..., -1.1734,  1.1021,  0.0402],
        [ 0.9568,  1.5606, -0.6954,  ...,  0.5781,  0.4220, -0.3824],
        [ 1.2265,  0.9574,  0.6961,  ..., -1.5957, -0.7074,  1.1243],
        ...,
        [-0.5327,  0.1168, -0.9735,  ...,  0.4644,  1.0863,  2.9835],
        [ 0.9745, -0.0585,  0.8191,  ...,  1.0286,  0.3149, -0.5704],
        [ 1.1581,  0.4691, -0.6013,  ..., -0.7145,  1.5498, -0.5195]])


In [114]:
mn = mnist_model(t)

torch.Size([60000, 1000])
torch.Size([60000, 100])
torch.Size([60000, 10])
torch.Size([60000, 10])


In [115]:
mn.shape

torch.Size([60000, 10])

# **Using nn.Parameters**

Parameters are Tensor subclasses, that have a very special property when used with Module - when they’re assigned as Module attributes they are automatically added to the list of its parameters, and will appear in parameters() iterator

Source:
- https://www.kdnuggets.com/2020/09/most-complete-guide-pytorch-data-scientists.html

# **Custom Linear Layer**

In [166]:
class myCustomLinearLayer(nn.Module):
    def __init__(self,in_size,out_size):
        super().__init__()
        self.weights = nn.Parameter(torch.randn(in_size, out_size))
        self.bias = nn.Parameter(torch.zeros(out_size))
    def forward(self, x):
        print(" Weights Shape: ", self.weights.shape)
        print(" Bias Shape: ", self.bias.shape)
        return x.mm(self.weights) + self.bias

# **Customer Neural Network**

In [167]:
class myCustomNeuralNet(nn.Module):
    def __init__(self):
        super().__init__()
        # Define all Layers Here
        self.lin1 = myCustomLinearLayer(784,10)
        
    def forward(self, x):
        # Connect the layer Outputs here to define the forward pass
        x = self.lin1(x)
        print(x.shape)
        return x

In [150]:
# ----- Input records and dimensions        
# 100 records of dimensions 784
x = torch.randn((100,784))

In [168]:
model = myCustomNeuralNet()

In [169]:
model

myCustomNeuralNet(
  (lin1): myCustomLinearLayer()
)

In [170]:
mm = model(x)

 Weights Shape:  torch.Size([784, 10])
 Bias Shape:  torch.Size([10])
torch.Size([100, 10])


In [154]:
mm.size()

torch.Size([100, 10])

In [155]:
mm.shape

torch.Size([100, 10])

# **Homework: Understanding Datasets and setting as input and output:**


- Titanic 
  - https://www.kaggle.com/c/titanic
  - Input - 12 columns including survived (output) columns
  - Output - Survived/Not Survived -> T/F || 1/0
  - 891 records
- Supermarket
- Loan Dataset


# **What is next?**
- How the data is loaded into a network?
- How transectional data is processed with PyTorch
- How the image data is processed with PyTorch

# **Supported Neural Network Architecture with PyTorch:**
- nn.Linear
- nn.Conv2d
- nn.MaxPool2d
- nn.ReLU
- nn.BatchNorm2d
- nn.Dropout
- nn.Embedding
- nn.GRU/nn.LSTM
- nn.Softmax
- nn.LogSoftmax
- nn.MultiheadAttention
- nn.TransformerEncoder
- nn.TransformerDecoder